// <auto-generated />
using System;
using Dokterspraktijk.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dokterspraktijk.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530203803_AfspraakCategorieToevoegen")]
    partial class AfspraakCategorieToevoegen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dokterspraktijk.Domain.Entities.Afspraak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DokterId")
                        .HasColumnType("int");

                    b.Property<string>("FotoBestandsnaam")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reden")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TijdslotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Afspraken");
                });

            modelBuilder.Entity("Dokterspraktijk.Domain.Entities.AfspraakCategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AfspraakCategorieen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Consultatie"
                        });
                });

            modelBuilder.Entity("Dokterspraktijk.Domain.Entities.Dokter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Specialisatie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Dokters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Timmermans",
                            Specialisatie = "Huisarts"
                        },
                        new
                        {
                            Id = 2,
                            Naam = "Brancaert",
                            Specialisatie = "Huisarts"
                        });
                });

            modelBuilder.Entity("Dokterspraktijk.Domain.Entities.Doktersattest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AfspraakId")
                        .HasColumnType("int");

                    b.Property<bool>("IsGedownload")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVrijgegeven")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Doktersattesten");
                });

            modelBuilder.Entity("Dokterspraktijk.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Rijksregisternummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefoonnummer")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("VoorkeursdokterId")
                        .HasColumnType("int");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Patienten");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Achternaam = "Laghmouchi",
                            Email = "rawan.laghmouchi@gmail.be",
                            Rijksregisternummer = "00.00.00-000.00",
                            Telefoonnummer = "0470123456",
                            Voornaam = "Rawan"
                        },
                        new
                        {
                            Id = 2,
                            Achternaam = "Vandenbogaerde",
                            Email = "Hans.Vandenbogaerde@gmail.be",
                            Rijksregisternummer = "11.11.11-111.11",
                            Telefoonnummer = "0470654321",
                            Voornaam = "Hans"
                        });
                });

            modelBuilder.Entity("Dokterspraktijk.Domain.Entities.Tijdslot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("DokterId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Tijd")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Tijdsloten");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Datum = new DateOnly(2026, 5, 15),
                            DokterId = 1,
                            Status = 1,
                            Tijd = new TimeOnly(10, 30, 0)
                        },
                        new
                        {
                            Id = 2,
                            Datum = new DateOnly(2026, 5, 15),
                            DokterId = 1,
                            Status = 2,
                            Tijd = new TimeOnly(9, 30, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
