<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
		<PackageReference Include="Reqnroll.xunit.v3" Version="3.2.0" />
		<PackageReference Include="xunit.v3" Version="3.0.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.3" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Drivers\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Dokterspraktijk.Application\Dokterspraktijk.Application.csproj" />
		<ProjectReference Include="..\..\src\Dokterspraktijk.Domain\Dokterspraktijk.Domain.csproj" />
		<ProjectReference Include="..\..\src\Dokterspraktijk.Infrastructure\Dokterspraktijk.Infrastructure.csproj" />
	</ItemGroup>

</Project>